name: Deploy BotFactory Configuration

on:
  workflow_dispatch:  # Allow manual triggering
    inputs:
      config:
        description: 'Select configuration file'
        required: true
        default: ''
        type: choice
        options:
          - AdminPrivilegedCloudUserORRoles
          - CloudUserWithAPICredentialsAccessKeyAgeExceeds90Days
          - CriticalResourceRiskScoreJIRATicketCreation
          - Critical&HighInsightVulnerabilities
          - DEV-RecentlyCreatedIAMUserORRole
          - DEV-AWSGuardDutyThreatFindings
          - PROD-RecentlyCreatedIAMUserORRole
          - PROD-AWSGuardDutyThreatFindings
          - ExemptionForFalcoServiceFromPrivilegedContainersInsight
          - ExemptionForFalcoServiceFromHighRiskHostFileSystemMountsInsight
          - ExemptionForEKSInstancesWhichContainSensitiveInformationWithinInstanceUserData
          - ExemptionForEKSInstancesFromMulti-TenantAWSInsightResource
          - InstancesWithPublicSSHAccess
          - StorageContainerExposedToThePublic

jobs:
  run-inline-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run BotFactory script inline
        working-directory: ./rapid7-config
        env:
          API_KEY: ${{ secrets.INSIGHT_API_KEY }}
        run: |
          CONFIG_FILE="${{ github.event.inputs.config }}.json"
          echo "Depoloying config file: $CONFIG_FILE"
          python deploy-bot.py --config "$CONFIG_FILE"
