name: Deploy BotFactory Configuration

on:
  workflow_dispatch:
    inputs:
      config:
        description: 'Select configuration file'
        required: true
        default: ''
        type: choice
        options:
          - rapid7-json-file
          - AdminPrivilegedCloudUserORRoles
          - CloudUserWithAPICredentialsAccessKeyAgeExceeds90Days
          - CriticalResourceRiskScoreJIRATicketCreation
          - Critical&HighInsightVulnerabilities
          - DEV-RecentlyCreatedIAMUserORRole
          - DEV-AWSGuardDutyThreatFindings
          - PROD-RecentlyCreatedIAMUserORRole
          - PROD-AWSGuardDutyThreatFindings
          - ExemptionForFalcoServiceFromPrivilegedContainersInsight
          - ExemptionForFalcoServiceFromHighRiskHostFileSystemMountsInsight
          - ExemptionForEKSInstancesWhichContainSensitiveInformationWithinInstanceUserData
          - ExemptionForEKSInstancesFromMulti-TenantAWSInsightResource
          - InstancesWithPublicSSHAccess
          - StorageContainerExposedToThePublic

jobs:
  setup:
    name: 🧰 Setup Environment
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

  install:
    name: 📦 Install Dependencies
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Check out repository
        uses: actions/checkout@v4  # Needed again because each job is a fresh VM

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  deploy:
    name: 🚀 Deploy BotFactory Configuration
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Deploy Selected Config
        working-directory: ./rapid7-config
        env:
          API_KEY: ${{ secrets.INSIGHT_API_KEY }}
        run: |
          CONFIG_FILE="${{ github.event.inputs.config }}.json"
          echo "Deploying config file: $CONFIG_FILE"
          python deploy-bot.py --config "$CONFIG_FILE"
