name: Run BotFactory Script Inline

on:
  workflow_dispatch:  # Allow manual triggering
    inputs:
      config:
        description: 'Select configuration file'
        required: true
        default: ''
        type: choice
        options:
          - Admin Privileged Cloud Users/Roles
          - Cloud User With API Credentials Access Key Age Exceeds 90 Days
          - Critical Resource Risk Score JIRA Ticket creation
          - Critical & High Insight Vulnerabilities
          - DEV - Recently Created IAM User or Role
          - DEV - AWS Guard Duty Threat Findings
          - PROD - Recently Created IAM User or Role
          - PROD - AWS Guard Duty Threat Findings
          - Exemption for Falco Service from Privileged Containers Insight
          - Exemption for Falco Service from High risk host file system mounts Insight
          - Exemption for EKS Instances which contain sensitive information in instance user data
          - Exemption for EKS Instances from Multi-Tenant (AWS) Insight Resource
          - Instances with Public SSH Access
          - Storage Container exposed to the public

jobs:
  run-inline-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run BotFactory script inline
        working-directory: ./rapid7-config
        env:
          API_KEY: ${{ secrets.INSIGHT_API_KEY }}
        run: |
          python deploy-bot.py
